services:
  backend:
    build: ./backend
    ports:
      - "3001:3001"
    environment:
      - NODE_ENV=development
    volumes:
     - ./backend:/app 
    restart: unless-stopped

  frontend:
    build: ./frontend
    ports:
      - "80:80"
    volumes:
      - ./frontend/src:/usr/share/nginx/html
    restart: unless-stopped
    depends_on:
      - backend