services:
  backend:
    build: ./backend
    ports:
      - "3001:3001"
    environment:
      - NODE_ENV=development
    volumes:
     - ./backend:/app 
    restart: unless-stopped
    networks:
      - app-network

  frontend:
    build: ./frontend
    ports:
      - "80:80"
    volumes:
      - ./frontend/src:/usr/share/nginx/html
      - ./frontend/nginx.conf:/etc/nginx/conf.d/default.conf  # Важно!
    restart: unless-stopped
    depends_on:
      - backend
    networks:
      - app-network
    environment:
      - NGINX_ENVSUBST_TEMPLATE_SUFFIX=.conf


# Создаем общую сеть
networks:
  app-network:
    name: chai_app-network  # Явно указываем имя сети
    driver: bridge
    attachable: true  # Добавьте эту строку
