
services:
  backend:
    build: ./backend
    ports:
      - "3001:3001"
    environment:
      - DB_HOST=db
      - DB_PORT=5432-co
      - DB_USER=postgres
      - DB_PASSWORD=12345
      - DB_NAME=postgres
    depends_on:
      - db
    volumes:
      - ./backend:/app  # Исправлено (пример маппинга)
    networks:
      - app-network

  db:
    image: postgres:17.4
    container_name: Tea
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=12345
      - POSTGRES_DB=postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5438:5432"
    networks:
      - app-network


  frontend:
    build: ./frontend
    ports:
      - "80:80"
    volumes:
      - ./frontend:/app  # Монтируем папку с кодом
      - /app/node_modules  # Исключаем node_modules
    environment:
      - VITE_WATCH_POLLING=true  # Критически важно для Docker!
      - CHOKIDAR_USEPOLLING=true
    stdin_open: true  # Для React
    tty: true         # Для React
    restart: unless-stopped
    depends_on:
      - backend
    networks:
      - app-network

volumes:
  postgres_data:

networks:
  app-network:
    driver: bridge